language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 # Only run the lowest and highest supported versions to reduce the load on travis-ci.org.
 - 5.4
 # - 5.5
 - 5.6
 # - 7.0 PHP7 will not be implemented below Moodle 3.0.1.

#matrix:
# allow_failures:
#  - php: 7.0

env:
 global:
  - MOODLE_BRANCH=MOODLE_29_STABLE
  - IGNORE_PATHS=amd/build,amd/src/affix.js,amd/src/bootstrap.js,amd/src/carousel.js,amd/src/fitvids.js,amd/src/jBreadCrumb.js
  # Ignore custom.css until CSSlint can be instructed to ignore lines for '[[setting:customcss]]'.
  # Also ignore generated CSS files.
  - IGNORE_NAMES=*.txt,custom.css,b*.css,e*.css,f*.css,m*.css
 matrix:
  - DB=pgsql PHPUNIT=true
  - DB=mysqli PHPUNIT=true

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config '$CFG->foo = "bar";'
  - moodle-plugin-ci add-config '$CFG->phpunit_prefix = "phpu_";'
  - moodle-plugin-ci add-config '$CFG->phpunit_dataroot = $CFG->dataroot;'
  - moodle-plugin-ci add-config '$CFG->phpunit_dbtype = $CFG->dbtype;'
  - moodle-plugin-ci add-config '$CFG->phpunit_dblibrary = "native";'
  - moodle-plugin-ci add-config '$CFG->phpunit_dbhost    = $CFG->dbhost;'
  - moodle-plugin-ci add-config '$CFG->phpunit_dbname    = $CFG->dbname;'
  - moodle-plugin-ci add-config '$CFG->phpunit_dbuser    = $CFG->dbuser;'
  - moodle-plugin-ci add-config '$CFG->phpunit_dbpass    = $CFG->dbpass;'

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
