language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 # Only run the lowest and highest supported versions to reduce the load on travis-ci.org.
 - 5.4
 # - 5.5
 - 5.6
 # - 7.0 PHP7 will not be implemented below Moodle 3.0.1.

#matrix:
# allow_failures:
#  - php: 7.0

env:
 global:
  - MOODLE_BRANCH=MOODLE_29_STABLE
  - IGNORE_PATHS=amd/build,amd/src/affix.js,amd/src/bootstrap.js,amd/src/carousel.js,amd/src/fitvids.js,amd/src/jBreadCrumb.js
  # Ignore custom.css until CSSlint can be instructed to ignore lines for '[[setting:customcss]]'.
  # Also ignore generated CSS files.
  - IGNORE_NAMES=*.txt,custom.css,b*.css,e*.css,f*.css,m*.css
 matrix:
  - DB=pgsql PHPUNIT=true
  - DB=mysqli PHPUNIT=true

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

before_script:
    - >
      if [ "$INSTALL" = 'true' -o "$PHPUNIT" = 'true' ];
      then
        # Copy generic configuration in place.
        cp config-dist.php config.php ;

        # Create the moodledata directory.
        mkdir -p "$HOME"/roots/base

        # The database name and password.
        sed -i \
          -e "s%= 'moodle'%= 'travis_ci_test'%" \
          -e "s%= 'password'%= ''%" \
          config.php ;

        # The wwwroot and dataroot.
        sed -i \
          -e "s%http://example.com/moodle%http://localhost%" \
          -e "s%/home/example/moodledata%/home/travis/roots/base%" \
          config.php ;

        if [ "$DB" = 'pgsql' ];
        then
          # Postgres-specific setup.
          sed -i \
            -e "s%= 'username'%= 'postgres'%" \
            config.php ;

          psql -c 'CREATE DATABASE travis_ci_test;' -U postgres;
        fi

        if [ "$DB" = 'mysqli' ];
        then
          # MySQL-specific setup.
          sed -i \
            -e "s%= 'pgsql'%= 'mysqli'%" \
            -e "s%= 'username'%= 'travis'%" \
            config.php;

          mysql -u root -e 'SET GLOBAL innodb_file_format=barracuda;' ;
          mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;' ;
          mysql -e 'CREATE DATABASE travis_ci_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;' ;
        fi

        if [ "$PHPUNIT" = 'true' ];
        then
          # Create a directory for the phpunit dataroot.
          mkdir -p "$HOME"/roots/phpunit

          # The phpunit dataroot and prefix..
          sed -i \
            -e "/require_once/i \\\$CFG->phpunit_dataroot = '\/home\/travis\/roots\/phpunit';" \
            -e "/require_once/i \\\$CFG->phpunit_prefix = 'p_';" \
            config.php ;

          # Initialise PHPUnit for Moodle.
          php admin/tool/phpunit/cli/init.php
        fi
      fi

script:
    ########################################################################
    # PHPUnit
    ########################################################################
    - >
      if [ "$PHPUNIT" = 'true' ];
      then
        vendor/bin/phpunit;
      fi

  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
